### ISSUE TITLE
Use raw github link?

### ISSUE THREAD

**Issue by kyleabeauchamp** [openadventure/Open-Adventure#7]
It might be nice if users could directly download the PDFs without having to click-through a github page.  

AFAIK, this involves changing the links at the following page:

http://www.geekguild.com/openadventure/#basicrulebook

before:

https://github.com/openadventure/Open-Adventure/blob/master/rulebook/biem/openadventure_basic.pdf

after:

https://raw.githubusercontent.com/openadventure/Open-Adventure/master/rulebook/biem/openadventure_basic.pdf

**Comment by openadventure** [comment]
@kyleabeauchamp great ideas! I've updated the links at http://www.geekguild.com/openadventure to point to the raw version of the files.
